### PR TITLE
rails 7.2 compatibility

### PR DESCRIPTION
**Pull request by jules-w2**

### CODE REVIEW

**Comment by TBenedyk** [comment]
Bump on this - I'm having to upgrade using @jules-w2 branch for now

**Comment by cassio-maletich** [comment]
I'm having trouble upgrading to Rails 7.2, too. Is it planned for merging anytime soon?

**Review by elopezm3 — APPROVED** [review]
Indeed, we need that, because if not it is creating conflicts with view components dependencies

**Comment by YusukeIwaki** [comment]
Very sorry for late review.
I will merge this and release the patch.

**Pull request merged**
